### PR TITLE
A couple of fixes...

### PR DESCRIPTION
**Pull request by kevmoo**
Look good? What details would you like for these?

### CODE REVIEW

**Comment by kevmoo** [comment]
Friends?

**Comment by kevmoo** [comment]
Hello?

**Comment by thecodejunkie** [comment]
Hi.. we will review these changes shortly.. doing some refactoring right now :)

**Comment by thecodejunkie** [comment]
Part of what is going in right now is a new implementation of the genericatalog.. the MefContrib.Hosting.Generics project is being removed in favor of another approach

**Comment by kevmoo** [comment]
Oh...wow. Yeah I just looked at origin...I'm way behind.

Don't bend over backwards. I should have kept up with master.

Thanks for getting back to me.

**Comment by thecodejunkie** [comment]
hehe no worries.. rebasing the master ontop of my fork now to pull in some massive changes in the convention stuff and there's even more to come :-)

**Pull request merged**
